services:
  zookeeper:
    image: 'confluentinc/cp-zookeeper:latest'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - '2181:2181'

  kafka:
    image: 'confluentinc/cp-kafka:latest'
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CREATE_TOPICS: >
        checkout.complete.v1:5:1,
        checkout.aggregate.v1:5:1

  redis-cluster:
    image: grokzen/redis-cluster:7.0.15
    environment:
      IP: 0.0.0.0
      BIND_ADDRESS: 0.0.0.0
    ports:
      - "7000-7005:7000-7005"
    hostname: redis-cluster