spring:
  jpa:
    open-in-view: false
  application:
    name: store
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    generate-unique-name: false
  data:
    redis:
      cluster:
        max-redirects: 3
        nodes:
          - redis://localhost:7000
          - redis://localhost:7001
          - redis://localhost:7002
          - redis://localhost:7003
          - redis://localhost:7004
          - redis://localhost:7005
  session:
    redis:
      flush-mode: on-save
server:
  port: 8091