spring:
  jpa:
    open-in-view: false
  application:
    name: store
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    generate-unique-name: false
  data:
    redis:
      cluster:
        nodes: 127.0.0.1:7000,127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003,127.0.0.1:7004,127.0.0.1:7005
        max-redirects: 3
  session:
    redis:
      flush-mode: on-save
server:
  port: 8091