spring:
  application:
    name: store
  datasource:
    generate-unique-name: false
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/store
      username: root
      password: master-password
    slave:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3307/store
      username: root
      password: slave-password
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      cluster:
        max-redirects: 3
        nodes:
          - redis://localhost:7000
          - redis://localhost:7001
          - redis://localhost:7002
          - redis://localhost:7003
          - redis://localhost:7004
          - redis://localhost:7005
  session:
    redis:
      flush-mode: on-save
server:
  port: 8091