STOP SLAVE;
CHANGE MASTER TO
    MASTER_HOST='master-db',
    MASTER_USER='root',
    MASTER_PASSWORD='master-password',
    MASTER_PORT=3306,
    MASTER_LOG_FILE='mysql-bin.000001',
    MASTER_LOG_POS=0,
    MASTER_CONNECT_RETRY=10;
START SLAVE;