spring:
  application:
    name: producer
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    generate-unique-name: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  cache:
    redis:
      time-to-live: 60000
      key-prefix: producer

server:
  port: 8089
